# Generated by Django 6.0.6 on 2026-06-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
