# Generated by Django 6.0.6 on 2026-06-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0002_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
